# Generated by Django 3.1 on 2020-08-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
