# Generated by Django 3.1 on 2020-09-17 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200917_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthdate',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата рождения'),
        ),
    ]
